<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>amazon</name>
   <tag></tag>
   <elementGuidId>83844f04-054b-4308-82ba-36903355bb3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;a-page&quot;]/div[1]/div[1]/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4635eafe-b8e6-4201-ba35-168b878bb2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;a-page&quot;]/div[1]/div[1]/div/a/i</value>
      <webElementGuid>c5258ae5-a39e-470e-aa85-12ff83da7c6f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
